sudo: false
addons:
  apt:
    packages:
      - apparmor-utils
language: python
python:
  - "2.7"
install:
  - "pip install -r test-requirements.txt"
script:
  - "nosetests --with-coverage --cover-package=xqueue_watcher --cover-xml"
after_script:
  - "pip install coveralls"
  - coveralls
branches:
    only:
      - master
